"""splent_feature_reset

Revision ID: 3d8f71d03199
Revises: 67338ae1583e
Create Date: 2026-03-21 23:56:24.024038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d8f71d03199'
down_revision = '67338ae1583e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
