"""splent_feature_reset

Revision ID: 3e5840fc469f
Revises: 3d8f71d03199
Create Date: 2026-03-22 23:10:23.432173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e5840fc469f'
down_revision = '3d8f71d03199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
