"""splent_feature_reset

Revision ID: 67338ae1583e
Revises: f18d29060de7
Create Date: 2026-03-21 23:53:13.257339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67338ae1583e'
down_revision = 'f18d29060de7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
