"""splent_feature_reset

Revision ID: f18d29060de7
Revises: 1c2ed70161dd
Create Date: 2026-03-21 18:54:00.732698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f18d29060de7'
down_revision = '1c2ed70161dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
